### ISSUE TITLE
Stability selection

### ISSUE THREAD

**Issue by viettr** [Leo-Simpson/classo#1]
![Bildschirmfoto 2020-11-12 um 15 28 52](https://user-images.githubusercontent.com/40998672/98952620-f1f9c000-24fb-11eb-9d55-c0a462d0a1a0.png)

I'm a little bit confused about the output of c-lasso. The text in the above example states that the selected variables are: 4,7,9,11,16 and 18. The plot on the other hand shows the variables 7,11,13,17,24,26. As far as I understood the output should select the same variables.

A small reproducible example:

`seed = 42`
`n,d,d_nonzero,k,sigma = 40,28,5,1,0.5
(X,C,y),sol = random_data(n, d, d_nonzero, k, sigma, zerosum=True,
                          classification=False, seed=seed, intercept=False)`
`print("X shape:", X.shape, "y values:", y, "C shape:", C.shape, sep = "\n")`
`problem = classo_problem(X,y,C) `
`problem.formulation.intercept = False`
`problem.formulation.classification = False`
`problem.formulation.huber = False`
`problem.model_selection.PATH = True`
`problem.solve()`
`print(problem)`

**Comment by Leo-Simpson** [comment]
Hello @viettr ,
Thank you for the report, there was a bug indeed on this due to a recent change. 
Now it is fixed in the latest version (1.0.0.7).

**Comment by viettr** [comment]
Hello @Leo-Simpson, 
it works perfectly. Just a comment: the readme seems to contain the old output and therefore can be a little bit confusing.
