### ISSUE TITLE
[JOSS review] Move the README into the documentation webpage

### ISSUE THREAD

**Issue by glemaitre** [Leo-Simpson/classo#10]
A README file is not really a documentation page. I would advise to move (or duplicate) the information on the documentation webpage.

**Comment by Leo-Simpson** [comment]
Dear @glemaitre,
Thank you for the comment. I have duplicate all the informations of the README to the documentation webpage (https://c-lasso.readthedocs.io/en/latest/). It has been just a little bit adapted to the structure of the webpage, but it is the same content.
