### ISSUE TITLE
[JOSS] add examples in the documentation

### ISSUE THREAD

**Issue by glemaitre** [Leo-Simpson/classo#12]
The examples have some path hardcoded and are not part of the documentation.
It would be best to make them part of the documentation using a tool as `sphinx-gallery` for instance.

As an example, you can refer to: https://mathurinm.github.io/celer/ to see my expectation

**Comment by Leo-Simpson** [comment]
Dear @glemaitre,

I have changed the location of the figures, hence I do not have hardcoded paths anymore, but only relative paths.

As mentionned in the previous issue, I have moved the readme content to the documentation. So it contains now a "getting started" part with some examples.

sphinx-gallery looks also very nice. I can incorporate this as well if you think it is better.

**Comment by glemaitre** [comment]
I will not require `sphinx-gallery` for the review but this is a nice thing to have :)

**Comment by Leo-Simpson** [comment]
I used sphinx-gallery, indeed it is much nicer to manage the examples. The four examples are now in the documentation.
