### ISSUE TITLE
[JOSS] assert in test

### ISSUE THREAD

**Issue by glemaitre** [Leo-Simpson/classo#14]
I quickly check the tests. I think that there is a number of places where you would benefit of using from the `numpy.testing` facilities as `assert_array_less`, `assert_allclose`, etc and from `pytest.approx` whenever you do floating comparison to manage the tolerance in a consistent way.

**Comment by Leo-Simpson** [comment]
Thank you for the comment. I am now using `numpy.testing.assert_allclose` for the tests.

**Comment by glemaitre** [comment]
Feel free to close the issues once that you addressed them :)
