### ISSUE TITLE
Content in setup.py

### ISSUE THREAD

**Issue by glemaitre** [Leo-Simpson/classo#15]
I think that you can add some metadata information regarding language, version and platform supported, e.g.
https://github.com/scikit-learn/scikit-learn/blob/master/setup.py#L241-L261

I would as well separate the requirements into default, test, doc: https://github.com/scikit-learn-contrib/imbalanced-learn/blob/master/setup.py#L38-L57 It is used by `pip` so it could be useful.

**Comment by Leo-Simpson** [comment]
It is done.
