### ISSUE TITLE
need a function to predict new data

### ISSUE THREAD

**Issue by bl6594** [Leo-Simpson/classo#18]
I split the data into training and test sets, and I would like to check how well the model built using the training data performs on the test data.  Can someone please provide me with a function that I can use to do the prediction?  I am primarily a R programmer with very limited knowledge in python.  Would really appreciate if someone can provide a function or give me a hint how I can proceed.

**Comment by viettr** [comment]
Here is an example that may be helpful: https://c-lasso.readthedocs.io/en/latest/auto_examples/example_CentralParkSoil.html#id1. It is also possible to run the model in R(https://jacobbien.github.io/trac/articles/trac-example.html#sparse-log-contrast).

**Comment by bl6594** [comment]
Thank you very much! This is exactly what I was looking for!

**Comment by bl6594** [comment]
Thank you very much! This is exactly what I was looking for!
