### ISSUE TITLE
[JOSS Review]: Automated tests

### ISSUE THREAD

**Issue by jbytecode** [Leo-Simpson/classo#4]
Dear authors,

Due to reviewing process in [JOSS](https://github.com/openjournals/joss-reviews/issues/2844):

There is a section 

> Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

in the reviewing list, however, it seems the software does not implement tests (at least unit tests). Please have a read on the unit testing in Python (for example [here](https://docs.python.org/3/library/unittest.html)) and implement tests for all of the functionality in the package.

Please add a `build and test` action in Actions part of the repository in [here](https://github.com/Leo-Simpson/c-lasso/actions) so when a commit is pushed, a triggered task will produce a report. You can also put a "PASSED" badge in your README.md file. Hence, the people can see whether the latest release works or not. 

Thank you in advance.

**Comment by Leo-Simpson** [comment]
Dear @jbytecode, thank you for your comment. I am currently working on that. I will tell you once it is ready.

Best regards.

**Comment by jbytecode** [comment]
Dear authors,

Since there is not any progress for this issue, I am writing here for just checking. Please let me know if you are in trouble.

Have a nice week.

**Comment by Leo-Simpson** [comment]
Dear @jbytecode,

I am still working on it, I will push my test files when they are ready, by the end of the week I hope, if it is ok.

Best regards.

**Comment by Leo-Simpson** [comment]
Dear @jbytecode , 

Automated tests for all functionalities are ready. There is also the GitHub action associated, so that the tests are automatically done at each commit.

Best regards.

**Comment by jbytecode** [comment]
Thank you. 

One more issue: I couldn't see any tests performed in file test_solver.py. Just function calls to solve(). Isnt it possible to check some values after performing this function?

**Comment by jbytecode** [comment]
One more issue: are you sure the tests are triggered in each single commit? What does ensure that in the action file? Yes it is right there is an action file but I couldnt see any tests performed. Just asking for checking.

**Comment by jbytecode** [comment]
Okay, I now see the stage

```
classo/tests/test_Classo_R.py ....                                       [  7%]
classo/tests/test_compact_func.py ..........                             [ 26%]
classo/tests/test_cross_validation.py ......                             [ 37%]
classo/tests/test_misc_func.py ..........                                [ 56%]
classo/tests/test_solver.py ............                                 [ 79%]
classo/tests/test_stability_selection.py ...........                     [100%]
```

I am closing this issue, but please add tests in test_solver.py if there is not any.

**Comment by Leo-Simpson** [comment]
Thank you for closing the issue.

I just wanted to mention that the correctness of the algorithms are checked more in test_Classo_R.py , because that is where it is checked that the different optimization scheme gives the same result (or a close result at least).

I can also add some checks in in the test of solver, but the idea there was just to check that everything assembled with no mistakes.

Also, just wanted to add that I will try to automatically add the html coverage report that is generated by the action to the repo, because this informs the percentage of the code that is covered.

Best regards.
