### ISSUE TITLE
[JOSS Review]: Community guidelines

### ISSUE THREAD

**Issue by jbytecode** [Leo-Simpson/classo#7]
Dear authors,

Due to manuscript submission in [JOSS](https://github.com/openjournals/joss-reviews/issues/2844)

There is an item in reviewing list that states

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

however the repository does not have the addressed items. This [page](https://github.com/Leo-Simpson/c-lasso/community) can be used to create one at least for `newcomers` (1). 

Please clearly indicate how to contribute this software, how can users create issues or report errors, and define a contact media (including e-mail or any other one) for those who needs help (I see an e-mail address in documentation, it is okay, but as addressed in the review items, it must be placed in repository in formal ways).  

Thank you in advance.

**Comment by Leo-Simpson** [comment]
Hello,

I added a  guideline for third parties  (https://github.com/Leo-Simpson/c-lasso/blob/master/CONTRIBUTING.rst), as well as a basic code of conduct (https://github.com/Leo-Simpson/c-lasso/blob/master/CODE_OF_CONDUCT.md).

I added a contact media in the end of the contributing file. I hope it is what you meant by placing it in formal ways.

Best regards.

**Comment by jbytecode** [comment]
seems okay, thank you!
